module Magic
  module Types
    Creatures = DryTypes::String.enum(
      *%w[
        Advisor
        Aetherborn
        Alien
        Ally
        Angel
        Antelope
        Ape
        Archer
        Archon
        Army
        Artificer
        Assassin
        Assembly-Worker
        Astartes
        Atog
        Aurochs
        Avatar
        Azra
        Badger
        Balloon
        Barbarian
        Bard
        Basilisk
        Bat
        Bear
        Beast
        Beeble
        Beholder
        Berserker
        Bird
        Blinkmoth
        Boar
        Bringer
        Brushwagg
        Camarid
        Camel
        Caribou
        Carrier
        Cat
        Centaur
        Cephalid
        Child
        Chimera
        Citizen
        Cleric
        Clown
        Cockatrice
        Construct
        Coward
        Crab
        Crocodile
        C’tan
        Custodes
        Cyclops
        Dauthi
        Demigod
        Demon
        Deserter
        Devil
        Dinosaur
        Djinn
        Dog
        Dragon
        Drake
        Dreadnought
        Drone
        Druid
        Dryad
        Dwarf
        Efreet
        Egg
        Elder
        Eldrazi
        Elemental
        Elephant
        Elf
        Elk
        Employee
        Eye
        Faerie
        Ferret
        Fish
        Flagbearer
        Fox
        Fractal
        Frog
        Fungus
        Gamer
        Gargoyle
        Germ
        Giant
        Gith
        Gnoll
        Gnome
        Goat
        Goblin
        God
        Golem
        Gorgon
        Graveborn
        Gremlin
        Griffin
        Guest
        Hag
        Halfling
        Hamster
        Harpy
        Hellion
        Hippo
        Hippogriff
        Homarid
        Homunculus
        Horror
        Horse
        Human
        Hydra
        Hyena
        Illusion
        Imp
        Incarnation
        Inkling
        Inquisitor
        Insect
        Jackal
        Jellyfish
        Juggernaut
        Kavu
        Kirin
        Kithkin
        Knight
        Kobold
        Kor
        Kraken
        Lamia
        Lammasu
        Leech
        Leviathan
        Lhurgoyf
        Licid
        Lizard
        Manticore
        Masticore
        Mercenary
        Merfolk
        Metathran
        Minion
        Minotaur
        Mite
        Mole
        Monger
        Mongoose
        Monk
        Monkey
        Moonfolk
        Mouse
        Mutant
        Myr
        Mystic
        Naga
        Nautilus
        Necron
        Nephilim
        Nightmare
        Nightstalker
        Ninja
        Noble
        Noggle
        Nomad
        Nymph
        Octopus
        Ogre
        Ooze
        Orb
        Orc
        Orgg
        Otter
        Ouphe
        Ox
        Oyster
        Pangolin
        Peasant
        Pegasus
        Pentavite
        Performer
        Pest
        Phelddagrif
        Phoenix
        Phyrexian
        Pilot
        Pincher
        Pirate
        Plant
        Praetor
        Primarch
        Prism
        Processor
        Rabbit
        Raccoon
        Ranger
        Rat
        Rebel
        Reflection
        Rhino
        Rigger
        Robot
        Rogue
        Sable
        Salamander
        Samurai
        Sand
        Saproling
        Satyr
        Scarecrow
        Scion
        Scorpion
        Scout
        Sculpture
        Serf
        Serpent
        Servo
        Shade
        Shaman
        Shapeshifter
        Shark
        Sheep
        Siren
        Skeleton
        Slith
        Sliver
        Slug
        Snake
        Soldier
        Soltari
        Spawn
        Specter
        Spellshaper
        Sphinx
        Spider
        Spike
        Spirit
        Splinter
        Sponge
        Squid
        Squirrel
        Starfish
        Surrakar
        Survivor
        Tentacle
        Tetravite
        Thalakos
        Thopter
        Thrull
        Tiefling
        Treefolk
        Trilobite
        Triskelavite
        Troll
        Turtle
        Tyranid
        Unicorn
        Vampire
        Vedalken
        Viashino
        Volver
        Wall
        Walrus
        Warlock
        Warrior
        Weird
        Werewolf
        Whale
        Wizard
        Wolf
        Wolverine
        Wombat
        Worm
        Wraith
        Wurm
        Yeti
        Zombie
        Zubera
      ]
    )
  end
end
